version: '3.7'

services:
  postgres:
    image: postgres:10.6-alpine
    container_name: cards_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbadmin